# Generated by Django 3.1.1 on 2020-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incomedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('workclass', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('education_num', models.IntegerField()),
                ('marital_status', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('capital_gain', models.IntegerField()),
                ('capital_loss', models.IntegerField()),
                ('hours_per_week', models.IntegerField()),
                ('native_country', models.CharField(max_length=100)),
            ],
        ),
    ]
